# Generated by Django 4.2.8 on 2023-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonialsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttestimonial',
            name='client_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
