# Generated by Django 4.2.8 on 2023-12-04 17:27

import InvestApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniqueid', models.CharField(max_length=20)),
                ('start_up_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('start_up_pic', models.ImageField(default=InvestApp.models.get_default_startup_pic, upload_to='images')),
                ('logo', models.ImageField(default=InvestApp.models.get_default_logo, upload_to='images')),
                ('about_startup_long', models.TextField()),
                ('about_startup_points', models.JSONField()),
                ('about_startup_short', models.CharField(max_length=255)),
                ('sector', models.JSONField()),
                ('tech', models.JSONField()),
                ('competitors', models.JSONField()),
                ('min_investment', models.IntegerField()),
                ('amount_raised', models.FloatField()),
                ('total_investor', models.IntegerField()),
                ('status_percentage', models.FloatField()),
                ('market_value', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('valuation_amount', models.IntegerField()),
                ('funding_goal', models.IntegerField()),
                ('type_of_instrument', models.CharField(max_length=255)),
                ('is_live', models.BooleanField()),
                ('deadline', models.DateField()),
                ('promo_code', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_sections', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_up_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default=InvestApp.models.get_default_logo, upload_to='images')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('sector', models.JSONField()),
                ('employee_strength', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Competitors', to='InvestApp.startup')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.ImageField(default='documents/default_document.jpg', upload_to='documents')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='InvestApp.startup')),
            ],
        ),
    ]
