# Generated by Django 4.2.8 on 2023-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Arts & Entertainment', 'Arts & Entertainment'), ('Consumer goods & Retails', 'Consumer goods & Retails'), ('Edtech', 'Edtech'), ('Fintech', 'Fintech'), ('Food & Drinks', 'Food & Drinks'), ('Health & wellness', 'Health & wellness'), ('Healthcare', 'Healthcare'), ('Real estate', 'Real estate'), ('Transpotation', 'Transpotation'), ('Travel & Hospitality', 'Travel & Hospitality')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='sector',
        ),
        migrations.AlterField(
            model_name='startup',
            name='about_startup_points',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='competitors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='custom_sections',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='startup',
            name='sector',
        ),
        migrations.AlterField(
            model_name='startup',
            name='tech',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='competitor',
            name='sector',
            field=models.ManyToManyField(to='InvestApp.sector'),
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.ManyToManyField(to='InvestApp.sector'),
        ),
    ]
