# Generated by Django 4.2.8 on 2023-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0002_sector_remove_competitor_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
