# Generated by Django 4.2.8 on 2023-12-04 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0005_alter_startup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
