# Generated by Django 4.2.8 on 2023-12-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0006_alter_startup_id'),
    ]

    operations = [
    ]
