# Generated by Django 4.2.8 on 2023-12-04 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0007_auto_20231204_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='sector',
        ),
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
