# Generated by Django 4.2.8 on 2023-12-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestApp', '0009_startup_sector_alter_startup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
